### PR TITLE
Win32 support

### PR DESCRIPTION
**Pull request by neutrino2211**
Addresses the windows related issues in #4 . The first commit adds cross-env for environment variables because `NODE_ENV=production` does not work on windows and the second commit fixes an unknown bug which passes down invalid parameters to the `taskkill` command.

### CODE REVIEW

**Comment by alex-saunders** [comment]
Hi @neutrino2211 , thanks so much for this PR!

Looks like the CI is failing on `yarn flow`, here's a screenshot of the error for your convenience:
Screenshot 2019-04-19 at 08 16 11

Do you think you'll be able to fix this?

Also would you be able to provide evidence of this working in Windows? It's a little hard for me to pull this down and test on a Windows machine so a video/screengrab of this working would be perfect.

**Comment by AWolf81** [comment]
@alex-saunders The flow issue seems fixed locally. I would try to re-run flow in circleci (with-out caching if possible). The last commit that added `toString` should fix the typing issue.

image

**Comment by neutrino2211** [comment]
@AWolf81 That was what I noticed too, it seems that Circle CI is still using 497e1d0

**Comment by alex-saunders** [comment]
@neutrino2211 are you able to update the cache key in the circleci `config.yml` and commit this? I'm not sure I can manually trigger a build without cache but updating the cache key should force it to generate a new cache for this PR. Perhaps update it to `v1.0.0.1`?

My CircleCI knowledge isn't great though so there might be another way of doing this.

**Comment by neutrino2211** [comment]
Currently breathing a huge sigh of relief. I believe I owe you guys an explanation for why I spammed your inboxes with "Workflow failed" emails 😅.

In f772b26 I tried generating a custom checksum from the `src` directory to use for the cache key but that failed due to the `shasum` command working differently in the CircleCI image than on my Linux machine.

Then in 212fc11, I changed the `shasum` command to something that would work on all *nix machines but that also failed, this time because the `.checksum` file created by the command is not kept between build jobs and the cache could not be restored

Finally, in 43676c3 I decided to use git commits to generate the cache key as directed by the CircleCI [documentation](https://circleci.com/docs/2.0/caching/#source-caching).

I believe using git commits to generate the cache key is better because using the `package.json` file to generate a key won't account for small code changes like the one I made in 80fb63d

**Comment by alex-saunders** [comment]
No problem at all @neutrino2211 , thank you for taking the time to dive into this problem!

Generating cache keys based off git commits sounds great to me and I'm happy to go with that solution. My only concern is how often the cache will be invalidated and the amount of 'cold start' builds that are going to be required, though I'm happy to see how it plays out over time.

Going back to the original aim of the PR - do you think you'd be happy to update the README to remove the section about Windows being unsupported (but maybe warn Windows users for unforeseen bugs?). I'm happy to merge this as is and update the README in a further PR, but it'd be great if we could bundle that in with this PR.

**Comment by neutrino2211** [comment]
@alex-saunders I would love to, and here is a picture of glicky running on windows
glicky-windows

**Pull request merged**
